"""DebateState — orchestration state model for the full debate lifecycle.

Tracks the complete state of a debate across all phases:
opinion generation, critique, revision, consensus, and evaluation.
Future phases will populate the currently unused fields.
"""

from dataclasses import dataclass, field


@dataclass
class OpinionRecord:
    """A single opinion generated by a participant model."""

    participant_id: str
    model_name: str
    content: str
    confidence_score: float | None
    response_id: str | None = None


@dataclass
class CritiqueRecord:
    """A single critique generated by one model targeting another's opinion.

    The target_opinion_id links back to the opinion being critiqued,
    enabling future persuasion and influence analysis.
    """

    participant_id: str
    model_name: str
    content: str
    confidence_score: float | None
    target_participant_id: str
    target_model_name: str
    target_response_id: str


@dataclass
class RevisionRecord:
    """A single revision generated by a participant after receiving critiques.

    The original_opinion_id links back to the opinion being revised,
    enabling future Opinion Drift calculations by comparing
    original and revised positions.
    """

    participant_id: str
    model_name: str
    content: str
    confidence_score: float | None
    original_opinion_id: str


@dataclass
class ConsensusRecord:
    """The final consensus artifact generated from revised positions."""

    consensus_score: float
    agreements: list[str] = field(default_factory=list)
    disagreements: list[str] = field(default_factory=list)
    summary: str = ""


@dataclass
class EvaluationRecord:
    """Evaluation results for a completed debate."""

    agreement_score: float = 0.0
    opinion_drifts: dict[str, float] = field(default_factory=dict)
    confidence_shifts: dict[str, float] = field(default_factory=dict)


@dataclass
class DebateState:
    """Orchestration state for a single debate session.

    Stores the complete lifecycle data. All phase fields are
    pre-defined so the state model doesn't need structural changes
    as new phases are added.
    """

    debate_id: str
    question: str
    participants: list[dict] = field(default_factory=list)
    opinions: list[OpinionRecord] = field(default_factory=list)
    critiques: list[CritiqueRecord] = field(default_factory=list)
    revisions: list[RevisionRecord] = field(default_factory=list)
    consensus: ConsensusRecord | None = None
    evaluation: EvaluationRecord | None = None
