"""Execution schemas — request/response models for debate execution endpoints."""

from pydantic import BaseModel, Field


class DebateRunRequest(BaseModel):
    """Request schema for starting debate execution."""

    rounds: int = Field(default=1, ge=1, le=10, description="Number of debate rounds")


class OpinionResult(BaseModel):
    """A single opinion generated by a participant model."""

    participant_id: str
    model_name: str
    content: str
    confidence_score: float | None = None


class CritiqueResult(BaseModel):
    """A single critique generated by one model targeting another's opinion.

    Links the critique to both the participant who generated it
    and the target opinion it addresses.
    """

    participant_id: str
    model_name: str
    content: str
    confidence_score: float | None = None
    target_participant_id: str
    target_model_name: str


class RevisionResult(BaseModel):
    """A single revised position generated after receiving critiques.

    Enables future Opinion Drift calculations by preserving
    the link between the revision and its original opinion.
    """

    participant_id: str
    model_name: str
    content: str
    confidence_score: float | None = None
    original_participant_id: str
    original_model_name: str


class ConsensusResult(BaseModel):
    """The final consensus artifact from the debate."""

    consensus_score: float
    agreements: list[str]
    disagreements: list[str]
    summary: str


class EvaluationResult(BaseModel):
    """Evaluation metrics computed for a completed debate."""

    agreement_score: float
    opinion_drifts: dict[str, float]
    confidence_shifts: dict[str, float]


class DebateRunResponse(BaseModel):
    """Response schema for debate execution results."""

    debate_id: str
    status: str
    opinions: list[OpinionResult]
    critiques: list[CritiqueResult] | None = None
    revisions: list[RevisionResult] | None = None
    consensus: ConsensusResult | None = None
    evaluation: EvaluationResult | None = None
